DROP TABLE IF EXISTS [ROLE_MASTER];
CREATE TABLE [ROLE_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) not null,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

--insertion of data into role master
INSERT INTO ROLE_MASTER([NAME],[IS_ACTIVE] )
VALUES ('Admin',0),('User',1);

SELECT *
FROM ROLE_MASTER;


----------------------------------------------------------

DROP TABLE IF EXISTS [OPERATING_UNIT_MASTER];
CREATE TABLE [OPERATING_UNIT_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) NOT NULL,
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO OPERATING_UNIT_MASTER([NAME])
VALUES ('Ameerpet'),('Madhapur');

 SELECT *
 FROM OPERATING_UNIT_MASTER;

 ------------------------------------------------------------

 DROP TABLE IF EXISTS [LEVEL_MASTER];
CREATE TABLE [LEVEL_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) NOT NULL,
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO LEVEL_MASTER([NAME])
VALUES ('L1'),('L2'),('L3');

 SELECT *
 FROM LEVEL_MASTER;

 ---------------------------------------------------------------------

 DROP TABLE IF EXISTS [FILE_ADDED];
CREATE TABLE [FILE_ADDED] (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
	[TICKET_ID_FK] INT NOT NULL,
	[CONTENT] VARBINARY(MAX)  DEFAULT NULL,    -- PICTURE UPLOAD
	[URL] VARCHAR(MAX) DEFAULT NULL,		   -- URL LINK		
	[IS_ACTIVE] BIT DEFAULT 0,
	[CREATED_AT] DATETIME DEFAULT GETDATE(),
	[UPDATED_AT] DATETIME DEFAULT GETDATE(),
	[CREATED_BY] VARCHAR(32) DEFAULT 'system',
	[UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO FILE_ADDED([TICKET_ID_FK])
VALUES (1),(2),(3),(21),(25);

 SELECT *
 FROM FILE_ADDED;

 ---------------------------------------------------------------------------------

DROP TABLE IF EXISTS [DEPARTMENT_MASTER];
CREATE TABLE [DEPARTMENT_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) not null,
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO DEPARTMENT_MASTER([NAME],[IS_ACTIVE] )
VALUES ('Development',1),
		('Recruitment',0),
		('Busineess Analyst',0),
		('Sales',0),
		('IT',1),
		('Management',0),
		('US Recruitment',0),
		('Finance',0);

SELECT *
FROM DEPARTMENT_MASTER;

-----------------------------------------------------------------------------

DROP TABLE IF EXISTS [STATUS_MASTER];
CREATE TABLE [STATUS_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) NOT NULL,
  [COLOR] VARCHAR(16) NOT NULL,
  [COLOR_CODE] VARCHAR(7) NOT NULL, -- HEX color code
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
);
GO

INSERT INTO STATUS_MASTER ([NAME], [COLOR], [COLOR_CODE])
VALUES 
  ('Open', 'BLUE', '#0000FF'),
  ('IN PROGRESS', 'YELLOW', '#FFFF00'),
  ('Resolved', 'GREEN', '#008000'),
  ('Invalid', 'BLOOD-RED', '#8B0000'),
  ('Temp Resolved', 'ORANGE', '#FFA500'),
  ('Escalted', 'RED', '#FF0000'),
  ('ACCEPTED', 'GREEN', '#008000'),
  ('Rejected', 'RED', '#FF0000'),
  ('Closed','GREY','#808080');

SELECT * 
FROM STATUS_MASTER;


----------------------------------------------------------------------------------

DROP TABLE IF EXISTS [LOGIN_LOG];
CREATE TABLE LOGIN_LOG(
  ID INT PRIMARY KEY IDENTITY(1,1),
  USER_NAME VARCHAR(32) NOT NULL,
  IS_LOGIN BIT DEFAULT 0,
  EMPLOYEE_ID_FK INT,
  IS_ACTIVE BIT DEFAULT 0,
  CREATED_AT DATETIME DEFAULT GETDATE(),
  UPDATED_AT DATETIME DEFAULT GETDATE(),
  CREATED_BY VARCHAR(32) DEFAULT 'system',
  UPDATED_BY VARCHAR(32) DEFAULT 'system'
);

INSERT INTO LOGIN_LOG(USER_NAME,IS_LOGIN,IS_ACTIVE)
VALUES ('Vevek',0,0),
('Shiva',0,1),
('Phanindra',1,1);

select * from LOGIN_LOG;
 

-------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS [CATEGORY_MASTER];
CREATE TABLE [CATEGORY_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) not null,
  [DESCRIPTION] VARCHAR(MAX) DEFAULT NULL,
  [LEVEL_ID_FK] INT,
  IS_WEB_ACTIVE BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO CATEGORY_MASTER([NAME],[DESCRIPTION],[LEVEL_ID_FK] )
VALUES 
('Admin','Website or DB Admin',3),
('HR','I solve People issues',1),
('IT','Wifi - Server - Laptop -Electronics',3),
('Finance','Come to me for any Finance Related issues.',1);

 SELECT *
 FROM CATEGORY_MASTER ; 
 

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS [SUB_CATEGORY_MASTER];
CREATE TABLE [SUB_CATEGORY_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(32) not null,
  CATEGORY_ID_FK INT,
-- OTHER_SUB_CATEGORY_NAME VARCHAR(32),     fill them in [sub_category.name]
  IS_WEB_ACTIVE BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)
GO

INSERT INTO SUB_CATEGORY_MASTER([CATEGORY_ID_FK],[NAME])
VALUES   
	(1, 'Server Management'),        -- Admin
	(1, 'Database Access'),          -- Admin
	(2, 'Recruitment'),              -- HR
	(2, 'Payroll Issues'),           -- HR
	(3, 'Laptop Request'),           -- IT
	(3, 'Wi-Fi Problems'),           -- IT
	(3, 'Software Installation'),    -- IT
	(4, 'Invoice Processing'),       -- Finance
	(4, 'Budget Approval');          -- Finance

SELECT *
FROM SUB_CATEGORY_MASTER;
GO


-----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS EMPLOYEE_MASTER
CREATE TABLE [EMPLOYEE_MASTER] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [FULL_NAME] VARCHAR(100) DEFAULT NULL,    -- derived column
  [FIRST_NAME] VARCHAR(100),
  [MIDDLE_NAME] VARCHAR(100) DEFAULT NULL,
  [LAST_NAME] VARCHAR(100),
  [EMAIL_SK] VARCHAR(100) CONSTRAINT EMAIL_CK CHECK(EMAIL_SK LIKE '%@sparity%.%'),
  [COUNTRY_CODE] VARCHAR(3) DEFAULT 91,
  [PHONE_SK] VARCHAR(15),
  [ROLE_ID_FK] INT,
  [OPERATING_UNIT_ID_FK] INT,
  [DEPARTMENT_ID_FK] INT,
  [LEVEL_ID_FK] INT DEFAULT NULL,
  [JOINED_AT] DATETIME,
  [MANAGER_ID] INT DEFAULT NULL,
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
)

---------------------------------------------------------------------------------

DROP TABLE IF EXISTS [EMPLOYEE_HISTORY];
CREATE TABLE [EMPLOYEE_HISTORY] (
  [ID] INT PRIMARY KEY IDENTITY(1,1),
  [EMPLOYEE_ID_FK] INT ,
  [FULL_NAME] VARCHAR(100) DEFAULT NULL, 
  [FIRST_NAME] VARCHAR(100),
  [MIDDLE_NAME] VARCHAR(100) DEFAULT NULL,
  [LAST_NAME] VARCHAR(100),
  [EMAIL_SK] VARCHAR(100),
  [COUNTRY_CODE] VARCHAR(3) DEFAULT 91,
  [PHONE_SK] VARCHAR(15),
  [ROLE_ID_FK] INT,
  [OPERATING_UNIT_ID_FK] INT,
  [DEPARTMENT_ID_FK] INT,
  [JOINED_AT] DATETIME,
  [MANAGER_ID] INT DEFAULT NULL,
  [LEVEL_ID_FK] INT DEFAULT NULL,
  [IS_WEB_ACTIVE] BIT DEFAULT 0,
  [IS_ACTIVE] BIT DEFAULT 0,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
);

------------------------------------------------------------------------

DROP TABLE IF EXISTS [TICKET]
CREATE TABLE [TICKET] (
  [ID]				INT PRIMARY KEY IDENTITY (1,1),
  [EMPLOYEE_ID_FK]	INT,
  RAISED_AT			DATETIME		DEFAULT GETDATE(),
  SUBJECT			VARCHAR(4000),
  DESCRIPTION		VARCHAR(4000),
  CATEGORY_ID_FK	INT,
  SUB_CATEGORY_ID	INT,
  RESOLUTION_DEADLINE DATETIME		DEFAULT NULL,
  ASSIGNED_TO		INT,
  STATUS_ID_FK		INT,
  IS_ACTIVE			BIT				DEFAULT 1,
  CREATED_AT		DATETIME		DEFAULT GETDATE(),
  UPDATED_AT		DATETIME		DEFAULT GETDATE(),
  CREATED_BY		VARCHAR(32)		DEFAULT 'SYSTEM',
  UPDATED_BY		VARCHAR(32)		DEFAULT 'SYSTEM'     
  -- [UPDATED_BY]  CAN BE USED BY L2 TO ASSIGN OR UPDATE [ASSIGNED_TO] STATUS
  CONSTRAINT EMP_FK FOREIGN KEY(EMPLOYEE_ID_FK)  REFERENCES EMPLOYEE_MASTER(ID)
  )

  EXEC sp_help 'TICKET';
 
-----------------------------------------------------------------------------------

DROP TABLE IF EXISTS [TICKET_HISTORY];
CREATE TABLE [TICKET_HISTORY] (
  [ID]       BIGINT       IDENTITY(1,1) PRIMARY KEY,
  [TICKET_ID_FK]     INT          NOT NULL,
  [EMPLOYEE_ID_FK]   INT,
  [RAISED_AT]        DATETIME,
  [SUBJECT]          VARCHAR(4000),
  [DESCRIPTION]      VARCHAR(4000),
  [CATEGORY_ID_FK]   INT,
  [SUB_CATEGORY_ID]  INT,
  [RESOLUTION_DEADLINE] DATETIME,
  [ASSIGNED_TO]      INT,
  [STATUS_ID_FK]     INT,
  [IS_ACTIVE]        BIT,
  [CREATED_AT]       DATETIME DEFAULT GETDATE(),
  [UPDATED_AT]       DATETIME DEFAULT GETDATE(),
  [CREATED_BY]       VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY]       VARCHAR(32) DEFAULT 'system'
);
GO


------------------------------------------------------------


DROP TABLE IF EXISTS [USER_TAG]
CREATE TABLE [USER_TAG] (
  [ID] INT PRIMARY KEY IDENTITY (1,1),
  [TICKET_ID_FK] INT,
  [MENTIONED_EMPLOYEE_ID] INT,
  [IS_APPROVER] BIT,
  [APPROVER_STATUS] INT,  -- STATUS MASTER LOOKUP 
  [IS_ACTIVE] BIT DEFAULT 1,
  [CREATED_AT] DATETIME DEFAULT GETDATE(),
  [UPDATED_AT] DATETIME DEFAULT GETDATE(),
  [CREATED_BY] VARCHAR(32) DEFAULT 'system',
  [UPDATED_BY] VARCHAR(32) DEFAULT 'system'
);

DROP TABLE IF EXISTS [Help_Desk_Employee]

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [ID] INT  NOT NULL;

ALTER TABLE [dbo].[Help_Desk_Employee]
ADD CONSTRAINT Help_Desk_Employee_PK PRIMARY KEY ([ID]);


 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [FULL_NAME] VARCHAR(100)
 
ALTER TABLE [dbo].[Help_Desk_Employee]
ADD CONSTRAINT DF_Help_Desk_Employee_FullName DEFAULT NULL FOR [FULL_NAME];


 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [FIRST_NAME] NVARCHAR(100) NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [MIDDLE_NAME] NVARCHAR(100) NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [LAST_NAME] NVARCHAR(100) NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [EMAIL_SK] VARCHAR(100) NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [COUNTRY_CODE] INT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [PHONE_SK] BIGINT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [ROLE_ID_FK] INT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [OPERATING_UNIT_ID_FK] INT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [DEPARTMENT_ID_FK] INT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [MANAGER_ID] INT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [JOINED_AT] DATETIME NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [IS_WEB_ACTIVE] BIT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [IS_ACTIVE] BIT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [CREATED_AT] DATETIME NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [UPDATED_AT] DATETIME NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [CREATED_BY] int NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [UPDATED_BY] int NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [CATEGORY_ID] INT NOT NULL;

 ALTER TABLE [dbo].[Help_Desk_Employee]
 ALTER COLUMN [LEVEL_ID_FK] INT NOT NULL;





alter TABLE [dbo].[Help_Desk_Employee]
alter column[ID] int  
alter column[ID] add constraint primary key
alter column[ID] add constraint NOT NULL,
	[FULL_NAME] varchar(32) NULL,
	[FIRST_NAME] varchar(32) NOT NULL,
	[MIDDLE_NAME] varchar(32) NULL,
	[LAST_NAME] varchar(32) NOT NULL,
	[EMAIL_SK] varchar(32) NOT NULL,
	[COUNTRY_CODE] int  NOT NULL,
	[PHONE_SK] bigint NOT NULL,
	[ROLE_ID_FK] int NULL,
	[OPERATING_UNIT_ID_FK] int NOT NULL,
	[DEPARTMENT_ID_FK] int NOT NULL,
	[MANAGER_ID] int NOT NULL,
	[JOINED_AT] datetime NOT NULL,
	[IS_WEB_ACTIVE] bit NOT NULL,
	[IS_ACTIVE] bit NOT NULL,
	[CREATED_AT] datetime NOT NULL,
	[UPDATED_AT] datetime NOT NULL,
	[CREATED_BY] varchar(50) NOT NULL,
	[UPDATED_BY] varchar(50) NOT NULL,
	[CATEGORY_ID] int NOT NULL,
	[LEVEL_ID_FK] int NOT NULL
) 
GO
